### PR TITLE
No unique resource

### PR DESCRIPTION
**Pull request by molinaro-m**
This pull request builds on the revert to v.1.03.
It must not be merged before #55 is merged, or reconsidered if it gets discarded.

It only relaxes the text for uniqueness of the RESOURCE(s) in the VOTable response

### CODE REVIEW

**Comment by molinaro-m** [comment]
This update has now been rebased on the revert to v.1.03.
Feel free to comment and review.
RESOURCE uniqueness drop doesn't affect uniqueness of type="results" RESOURCE in ConeSearch.

**Review by msdemlei — APPROVED** [review]
I'm fine with the intent and the form of this change.

Github right now considers this a 9 commit-PR.  I have not tried to figure out what confuses the history it sees, but I'd be confident that nothing bad will happen if you squash and merge.  If, on the other hand, you insist on a merge commit, I'd first try what happens locally...

**Comment by msdemlei** [comment]
(and if you give me write privileges, I expect the merge block should be lifted, too)

**Review by gmantele — APPROVED** [review]
This PR seems OK to me :+1:

**Pull request merged**
